---
- hosts: homelab
  become: true
  tasks:
    - name: CHOWN MEDIA FILES
      ansible.builtin.shell:
        cmd: chown -R mpowe:mpowe /data/Media
        chdir: /data
      args:
        executable: /bin/bash
