---
- hosts: homelab
  tasks:
    - name: CHOWN MEDIA FILES
      become: true
      ansible.builtin.shell:
        cmd: sudo chown -R mpowe:mpowe /data/Media
        chdir: /data
      args:
        executable: /bin/bash
